version: '3.8'

services:
  # 1. Message Broker (Fronta)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: siem-rabbitmq
    ports:
      - "5672:5672"   # Pro aplikace
      - "15672:15672" # Dashboard
    hostname: my-rabbit
    
    # 2. RTAP Cache (Počítadla útoků)
    # Rychlá paměť pro detekci útoků v reálném čase.
  redis:
    image: redis:alpine
    container_name: siem-redis
    ports:
      - "6379:6379"

  # 3. Search Database (Ukládání logů)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: siem-elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  # 4. Vizualizace (Dashboardy)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: siem-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://siem-elastic:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch